### ISSUE TITLE
Using Flexible Pickaxe crashes the game.

### ISSUE THREAD

**Issue by Zemogiter** [KidsDontPlay/Tools#10] opened 2017-08-05 09:58 UTC
When mining blocks using Flexible Pickaxe (with Range 3x3 upgrade) the game crashes. The kind of stone being mined dosen't seem to matter.

https://openeye.openmods.info/crashes/8d4c950e4ed8847cb189cb13d2aa11a3

**Comment by KidsDontPlay** [comment] 2017-08-05 14:40
duplicate of #9

**Closed as completed by KidsDontPlay** 2017-08-05 14:40 UTC
Labels: duplicate
