### ISSUE TITLE
Range Upgrade interaction with IE Multiblocks

### ISSUE THREAD

**Issue by davqvist** [KidsDontPlay/Tools#8] opened 2017-08-02 14:59 UTC
MC 1.12
Forge 2443
FT 1.2.3

A FT 3x3 Pickaxe breaking an IE Coke Oven drops the whole multiblock instead of the block consisting in it. I assume other multiblocks cause the same issue.

**Comment by KidsDontPlay** [comment] 2017-08-02 15:04
duplicate of #7
blusunrize will fix this.

**Closed as completed by KidsDontPlay** 2017-08-02 15:04 UTC
Labels: duplicate

**Comment by davqvist** [comment] 2017-08-02 15:06
Oh sorry I didn't check closed issues, only open ones. thanks.
